### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by jonasraoni** [asmecher/beacon#1]
@asmecher, I've created this issue just to keep track of my PR.

I did some initial refactoring in the code, mostly to remove duplicated things, updated the packages and added code-linting (I took the rules from Nate's PR), so nothing great to watch yet 😁

**Comment by jonasraoni** [comment]
It's just a draft, later I'll add some comments, test if everything is working fine and start adding the meat.

**Comment by asmecher** [comment]
The beacon code is already running on the PKP server, so merging this will mean some work on the cron job to make sure that the scripts are being executed in their new homes and details like database connection configuration, where they are changed, don't break the job. As you move from refactoring to adding new features, please keep that separate from the refactor commits, so changes can be reviewed separately from housekeeping.

**Comment by jonasraoni** [comment]
Thanks for the note! I was going to add the features over this draft.
Since I didn't change much the code, it won't be a big deal to merge it later.

**Comment by jonasraoni** [comment]
I've tested yesterday and everything seems to be working fine.
Before marking it ready for review/merge, I'll run both versions against a bigger log sample and check if the generated records match...

**Comment by asmecher** [comment]
@jonasraoni, at this point it makes sense to finish up the refactor, but please watch how much time you're spending on it; it's not work I would have recommended (at least until later), and doing it now actually complicates things.
